### PR TITLE
Infinite loop on `heroku logs --tail` retry

### PR DESCRIPTION
**Pull request by fancyremarker**
If a `heroku logs --tail` invocation succeeds (or exits with `Errno::EIO` or `IOError` instead of `PTY::ChildExited` on the second retry, we end up in an infinite loop, as demonstrated in the following logs from one of our apps:

```
21:04:05 Restarting heroku logs -p run.8151 --tail --app foobar-app, 1 retry left.
21:04:05 Running: heroku logs -p run.8151 --tail --app foobar-app
22:04:12 Started: 20226
22:04:12 Waiting: 20226
22:04:12 Running: heroku logs -p run.8151 --tail --app foobar-app
22:04:18 Started: 20253
22:04:18 Waiting: 20253
22:04:18 Restarting heroku logs -p run.8151 --tail --app foobar-app, -1 retries left.
22:04:18 Running: heroku logs -p run.8151 --tail --app foobar-app
23:04:24 Started: 20264
23:04:25 Waiting: 20264
23:04:25 Restarting heroku logs -p run.8151 --tail --app foobar-app, -2 retries left.
23:04:25 Running: heroku logs -p run.8151 --tail --app foobar-app
00:04:31 Started: 20300
00:04:31 Waiting: 20300
```

I'm happy to write a spec for this, but could use a recommendation on the best way to stub the causing behavior inside `Heroku::Executor`.

### CODE REVIEW

**Comment by dblock** [comment]
It's a real bug, so thank you. I don't think this fixes the problem though. Here's a spec that will loop indefinitely (modeled after one in runner_spec.rb).

``` ruby
    context "tail_retries IOError" do
      before :each do
        Heroku::Executor.stub(:run).with(subject.send(:cmdline, { :detached => true }), { :logger => nil }).
          and_yield("Running `ls -1` detached... up, run.8748").
          and_yield("Use `heroku logs -p run.8748` to view the output.").
          and_yield("rc=0").
          and_return([ "Running `ls -1` detached... up, run.8748", "Use `heroku logs -p run.8748` to view the output.", "rc=0" ])
        # first iteration
        Heroku::Executor.should_receive(:run).with("heroku logs -p run.8748 --tail", { :logger => nil }).
          and_yield("2013-01-31T01:39:30+00:00 heroku[run.8748]: Starting process with command `ls -1`").
          and_yield("2013-01-31T01:39:31+00:00 app[run.8748]: bin").
          and_return([
            "2013-01-31T01:39:30+00:00 heroku[run.8748]: Starting process with command `ls -1`",
            "2013-01-31T01:39:31+00:00 app[run.8748]: bin",
          ])
        # second iteration that raises IOError
        Heroku::Executor.should_receive(:run).with("heroku logs -p run.8748 --tail", { :logger => nil }).
          and_raise(IOError)
        Heroku::Runner.any_instance.should_receive(:terminate_executor!).twice
      end
      it "restarts tailer" do
        lines = []
        subject.run!({ :detached => true }).each do |line|
          lines << line
        end
        lines.should == [ "bin", "app", "" ]
        subject.pid.should == "run.8748"
        subject.should_not be_running
      end
    end
```

Please also do add a line to the CHANGELOG.

**Comment by fancyremarker** [comment]
Thanks for the spec suggestion – it replicates the issue perfectly! I'll commit a fix and update the CHANGELOG.

**Comment by fancyremarker** [comment]
OK. I think I fixed the behavior. I modified your spec a bit; it turns out that stubbing a `raise_error` inside a method that would normally catch it actually bypasses any `rescue` block. So I stubbed it to return `nil` instead, which should correctly replicate what happens when an exception is caught in `Heroku::Executor.run` (and is in fact more generic).

One more note: in your original implementation, the raised exception was an unnamed `RuntimeError`. I didn't change that behavior. If you have a preferred new `Exception` class, message, etc. I'm happy to add that here.

**Comment by dblock** [comment]
Great, thanks.

**Pull request merged**
